Aplication/Models/ErrorViewModel.cs
namespace Aplication.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Aplication/Controllers/EstatusController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Core.Entidades;
using Infraestructura.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Aplication.Controllers
{
    
    public class EstatusController : Controller
    {
        private readonly Contexto contexto;
        public EstatusController(Contexto contexto)
        {
            this.contexto = contexto;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var estatus= await contexto.Estatus.ToListAsync();
            return View(estatus);
        }
        [HttpGet]
        public async Task<IActionResult> Detail()
        {
            //var estatusModel= await contexto.Estatus.FindAsync(2);
            var estatusModel= await contexto.Estatus.FirstAsync(e=>e.Nombre=="Bueno");
            return View(estatusModel);
        }
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Estatus estatus)
        {
            if (ModelState.IsValid)
            {
                estatus.FechadeAlta=DateTime.Now;
                await contexto.AddAsync(estatus);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var estatus=await contexto.Estatus.FindAsync(id);
            if (estatus==null)
            {
                return NotFound();
            }
            return View(estatus);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id,Estatus estatus)
        {
            if (ModelState.IsValid)
            {
                contexto.Update(estatus);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var estatus=await contexto.Estatus.FindAsync(id);
            if (estatus==null)
            {
                return NotFound();
            }
            return View(estatus);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id,Estatus estatus)
        {
            if (ModelState.IsValid)
            {
                contexto.Remove(estatus);
                await contexto.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            

            return View();
        }
     
    }
    

    
}

Aplication/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Aplication.Models;

namespace Aplication.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Aplication/Views/Estatus/Crear.cshtml
@using Core.Entidades
@model Estatus

<div>
    <form asp-action="Crear">
        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input type="text" asp-for="Nombre" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Descripcion" class="control-label"></label>
            <input type="text" asp-for="Descripcion" class="form-control">
        </div>
        <div class="form-group">
            <input type="submit" value="Crear" class="btn btn-primary">
        </div>
    </form>
</div>

Aplication/Views/Estatus/Delete.cshtml
@using Core.Entidades
@model Estatus

<div>
    <form asp-action="Delete">
        <input type="text" asp-for="Id">
        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input type="text" asp-for="Nombre" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Descripcion" class="control-label"></label>
            <input type="text" asp-for="Descripcion" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="FechadeAlta" class="control-label"></label>
            <input readonly type="text" asp-for="FechadeAlta" class="form-control">
        </div>
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-primary">
        </div>
    </form>
</div>

Aplication/Views/Estatus/Index.cshtml
@using Core.Entidades
@{
    ViewData["Title"] = "Lista de Estatus";
}
@model List<Estatus>
<p>Estatus</p>
<ul>
@foreach(var item in Model){
<li>
    @item.Nombre
</li>
}
</ul>

Aplication/Views/Estatus/Update.cshtml
@using Core.Entidades
@model Estatus

<div>
    <form asp-action="Update">
        <input type="text" asp-for="Id">
        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input type="text" asp-for="Nombre" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Descripcion" class="control-label"></label>
            <input type="text" asp-for="Descripcion" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="FechadeAlta" class="control-label"></label>
            <input readonly type="text" asp-for="FechadeAlta" class="form-control">
        </div>
        <div class="form-group">
            <input type="submit" value="Editar" class="btn btn-primary">
        </div>
    </form>
</div>

Aplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Aplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Aplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estatus" asp-action="Index">Estatus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estatus" asp-action="Crear">Crear Estatus</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Aplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>